### ISSUE TITLE
Request to revise syntax error

### ISSUE THREAD

**Issue by YeongHyeon** [7fantasysz/MSCRED#3]
1. In 'matrix_generator.py'...
It has indentationError in line 188, because it has wrote by mixing tab and space.
Can you replace all the space to tab?

2. in 'MSCRED_TF.py'...
The command for calling pandas has blocked by commented out.
Can you remove '#' in line 4?

**Comment by tgb1233** [comment]
It has indentationError in line 188, because it has wrote by mixing tab and space.
Can you replace all the space to tab，I have the same problem,please tell me how to sovle the trouble please.

**Comment by HongminWu** [comment]
I encountered the same indentationError, would you revise it? @7fantasysz

**Comment by tgb1233** [comment]
Hi
I have been doing research on deep time series, and we have been communicating and discussing together as friends


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"HongminWu"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月17日(星期二) 中午11:51
收件人:&nbsp;"7fantasysz/MSCRED"<MSCRED@noreply.github.com&gt;;
抄送:&nbsp;"血红的枫の叶"<1084783659@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [7fantasysz/MSCRED] Request to revise syntax error (#3)




I encountered the same indentationError, would you revise it? @7fantasysz

**Comment by HongminWu** [comment]
你是吴佳敏？ 你解决了MSCRED中关于缩进的问题么？ Hongmin Wu Email:hongminwu0120@gmail.com Signature is customized by Netease Mail Master On 12/17/2019 11:55, tgb1233 wrote: Hi I have been doing research on deep time series, and we have been communicating and discussing together as friends ------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;"HongminWu"<notifications@github.com&gt;; 发送时间:&nbsp;2019年12月17日(星期二) 中午11:51 收件人:&nbsp;"7fantasysz/MSCRED"<MSCRED@noreply.github.com&gt;; 抄送:&nbsp;"血红的枫の叶"<1084783659@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;; 主题:&nbsp;Re: [7fantasysz/MSCRED] Request to revise syntax error (#3) I encountered the same indentationError, would you revise it? @7fantasysz — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by 7fantasysz** [comment]
thanks for comments, fixed. This repo is not being actively maintained. Response will be slow.
